# fly.toml app configuration file generated for cryobot1 on 2023-10-23T23:06:36-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cryobot1"
primary_region = "sjc"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_start_machines = true
  auto_stop_machines = false  # prevent automatic suspension
  min_machines_running = 1  # keep a machine running at all times